### ISSUE TITLE
Error after install 

### ISSUE THREAD

**Issue by neomen** [UWHealth/markdown-documentation-generator#1]
When I tried to initialize "md_documentation init", I got this error

/home/vagrant/000/blabla/node_modules/markdown-documentation-generator/index.js:68
        let configFilePath = path.join(process.cwd(), '.styleguide'),
        ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "styleguide"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! mint@1.0.0 styleguide: `md_documentation init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mint@1.0.0 styleguide script 'md_documentation init'.
npm ERR! This is most likely a problem with the mint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     md_documentation init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/000/mint/npm-debug.log

**Comment by Cleecanth** [comment]
I believe this is caused by an outdated version of node. 

If you're able to update your version of Node (preferably to 6.0+), please do and retry.

This does bring up an interesting point though: I should probably figure out the minimum Node version for this project and add a warning if that version isn't met.

**Comment by neomen** [comment]
I think you're right. I've updated nodejs to 7.2.1 and after that everything worked fine. 

Thank you.
