### ISSUE TITLE
Remove stickykit from default template

### ISSUE THREAD

**Issue by neomen** [UWHealth/markdown-documentation-generator#2]
The generated document contains an error in javascript

Uncaught TypeError: $(...).stick_in_parent is not a function(…)(anonymous function) @ styleguide.html:453j @ styleguide.html:437fireWith @ styleguide.html:437ready @ styleguide.html:437I @ styleguide.html:437

I think you would like to include and use this library http://leafo.net/sticky-kit but did not implement this feature.

**Comment by Cleecanth** [comment]
The script tag at the bottom of the base template can be removed completely.

While working on example templates (soon to come), that reference somehow made its way into the main template.

If you want to use sticky-kit, you can point to `node_modules/markdown-documentation-generator/template/sticky.js`.

**Comment by Cleecanth** [comment]
Fixed in e67cfd021438d68c7a6f284a55489fa23f193c7d
