### ISSUE TITLE
Generated .styleguide from --init flag does not work.

### ISSUE THREAD

**Issue by luigimannoni** [UWHealth/markdown-documentation-generator#9]
There has been a change recently on the project to migrate from old json configs to accept javascript files/objects, I can pin point the issue appearing after 3.0.1, updating the module breaks the generator using the old json file with no deprecation warning issued.

Generating a new `.styleguide` file from the tool itself does not help alleviating the issue.  

```
$ node node_modules/.bin/md_documentation --init
$ node --trace-warnings node_modules/.bin/md_documentation --lf

[Style Guide]  Reading Configuration
node_modules/markdown-documentation-generator/index.js:216
            throw new Error(_sg.error(err));
            ^

Error: SyntaxError: Unexpected token ':'.
    Check your configuration and try again.
    at registerConfig (node_modules/markdown-documentation-generator/index.js:216:19)
    at init (node_modules/markdown-documentation-generator/index.js:751:15)
    at node_modules/markdown-documentation-generator/index.js:811:9
    at Object.<anonymous> (node_modules/markdown-documentation-generator/index.js:813:2)

```

If I edit the module manually to print out the full error including the stack this is what I get:

```
.styleguide:2 Error: SyntaxError: Unexpected token ':'.

"sgComment": "SG",
           ^
```

Happening on latest version published on npm (v3.2.1)

**Comment by luigimannoni** [comment]
I eventually fixed the issue today by renaming the config file into `.stylelint.json`, looks like node won't load the json correctly if it does not have the correct file extension.

**Comment by stantonl33** [comment]
> 
> 
> I eventually fixed the issue today by renaming the config file into `.stylelint.json`, looks like node won't load the json correctly if it does not have the correct file extension.

I'm getting this same error and tried renaming the .styleguide file to .stylelint.json like you mentioned but then got an error saying there was not .styleguide file...What file did you rename exactly?

`Error: Error: Cannot find module 'C:\inetpub\catalog\.styleguide'
Require stack:
- C:\Users\..\AppData\Roaming\npm\node_modules\markdown-documentation-generator\index.js.
    Check your configuration and try again.`

**Comment by luigimannoni** [comment]
I have forked the package myself and published an updated version. Try `npm install --save @deimosindustries/markdown-documentation-generator`
